In [7]:
import numpy as np
import pandas as pd
labelDf = pd.DataFrame({'one':['c','b','c'],'two':['c','a','b']})
labelDf

one two
0   c   c
1   b   a
2   c   b

In [8]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [9]:
le = LabelEncoder()
ohe = OneHotEncoder(sparse=False) 

In [34]:
# directly deal with dataframes
for col in labelDf.columns:
    labelDf[col]=le.fit_transform(labelDf[col])
print(labelDf)
oheList = ohe.fit_transform(labelDf)
print(oheList)

   one  two
0    1    2
1    0    0
2    1    1
[[ 0.  1.  0.  0.  1.]
 [ 1.  0.  1.  0.  0.]
 [ 0.  1.  0.  1.  0.]]


In [10]:
# column by column
oheList = []
for col in labelDf.columns:
    le.fit(labelDf[col])
    feature = le.transform(labelDf[col])
    feature=feature.reshape(labelDf.shape[0], 1)
#     ohe = OneHotEncoder(sparse=False,n_values=len(labels[i]))
    feature = ohe.fit_transform(feature)
    oheList.append(feature)
oheList = np.column_stack(oheList)
print(labelDf)

print(oheList)

  one two
0   c   c
1   b   a
2   c   b
[[ 0.  1.  0.  0.  1.]
 [ 1.  0.  1.  0.  0.]
 [ 0.  1.  0.  1.  0.]]


In [6]:
oheList

[array([[ 0.,  1.],
        [ 1.,  0.],
        [ 0.,  1.]]), array([[ 0.,  0.,  1.],
        [ 1.,  0.,  0.],
        [ 0.,  1.,  0.]])]